server:
  port: 8001
spring:
  datasource:
    url: "jdbc:mysql://172.19.7.242:3306/spring_cloud_demo?useUnicode=true&zeroDateTimeBehavior=convertToNull"
    username: "root"
    password: "aisino123."
oauth2:
  private-key:
    path: "jwt_keypair.jks"
    alias: "jwt"
    password: "KCPzQVp8VVyHV9Ds"