server:
  port: 8001
spring:
  datasource:
    url: "jdbc:mysql://172.19.7.242:3306/spring_cloud_demo?useUnicode=true&zeroDateTimeBehavior=convertToNull"
    username: "root"
    password: "aisino123."
oauth2:
  private-key:
    path: "jwt_keypair.jks"
    alias: "jwt"
    password: "KCPzQVp8VVyHV9Ds"
    
eureka:
  port: 8761
  username: discovery
  password: 3GfhPZQifTpVcu
  client:
    registry-fetch-interval-seconds: 5
    service-url:
#      defaultZone: http://${eureka.username}:${eureka.password}@eureka1:${eureka.port}/eureka,http://${eureka.username}:${eureka.password}@eureka2:${eureka.port}/eureka
      defaultZone: http://${eureka.username}:${eureka.password}@localhost:${eureka.port}/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10